name: CI/CD pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout version control
        uses: actions/checkout@v2
    
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install python dependencies
        run: |
          python3 -m pip install -r requirements.txt
          echo "Launching webserver in the background ..."
          cd my_web_api 
          nohup python3 -m uvicorn main:app --reload &
          cd -

      - name: Run Tests
        run: |
          echo "Running test cases..."
          python3 -m pytest
          
